### PR TITLE
Make compatible with IntelliJ IDEA 2020.3

### LINKED ISSUE #49: Not compatible with IntelliJ IDEA 2020.3
When trying to upgrade IntelliJ IDEA 2020.2.4 to 2020.3 (IC-203.5981.155):
Screenshot 2020-12-02 at 05 00 27

### PR DESCRIPTION
**Pull request by nicokosi**
Fix https://github.com/madplay/Mad-jEnv/issues/49

- [x] It builds on my machine (`./gradlew build`)
- [x] I can install it in IntelliJ IDEA 2020.3 and it "works"

### CODE REVIEW

**Comment by nicokosi** [comment]
For information, `./gradlew build` succeeds on my machine but this error is logged:
> 2020-12-02 05:25:53,080 [  18570]  ERROR - tellij.openapi.util.ObjectTree - Memory leak detected: 'org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab@71352224' of class org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab

I don't know if this is related to the fact that the `Kotlin` plugin is also not compatible with IDEA 2020.3. 🤔

Full error logs: [build-error.log](https://github.com/madplay/Mad-jEnv/files/5626955/build-error.log)

**Comment by nicokosi** [comment]
Upgraded IntelliJ IDEA to 2020.3 (Community Edition Build #IC-203.5981.155) and installed MadEnv from disk (`./build/distributions/Mad-jEnv-1.3.zip`). ✅ 
I tried to smoke test the `Mad-jEnv` plugin declaring a new JDK version (JDK 16) via `jenv add` but is it not detected in IDEA 🤔 :
Screenshot 2020-12-02 at 06 22 11
Screenshot 2020-12-02 at 06 21 14

IDEA logs contains:
> 2020-12-02 06:31:43,972 [  69322]   INFO - lij.ide.plugins.DynamicPlugins - Can't resolve optional dependency on plugin being loaded/unloaded: config file duplicates-detection-groovy.xml
 
See [idea.log](https://github.com/madplay/Mad-jEnv/files/5627203/idea.log)

**Comment by nicokosi** [comment]
For information, generated ZIP is [Mad-jEnv-1.3.zip](https://github.com/madplay/Mad-jEnv/files/5627147/Mad-jEnv-1.3.zip).

**Comment by nicokosi** [comment]
After adding JDK 16 in `jenv`, I can add it in IntelliJ IDEA 2020.3 this way (I initially thought it would "auto-synch"):
Screenshot 2020-12-03 at 06 00 38

I think it is somewhat related to https://github.com/madplay/Mad-jEnv/issues/47. 😇

**Comment by madplay** [comment]
I appreciate it. You helped me a lot.
I'm up to my ears in work these days :(

**Pull request merged**
